### ISSUE TITLE
 Procnuke doesn't work on Linux Mint. Libc version is incorrect.

### ISSUE THREAD

**Issue by FriskIsGit** [Kihau/procnuke#1]
ERROR:
procnuke: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33 not found (required by procnuke)
procnuke: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32 not found (required by procnuke)
procnuke: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found (required by procnuke)

OS:
Linux Mint 20 x86_64

Kernel:
5.4.0-60-generic

**Comment by Kihau** [comment]
You can compile for the `x86_64-unknown-linux-musl` target or statically link glibc to emit binary that works on all linux systems...
```sh
$ cargo build --target x86_64-unknown-linux-musl --release
```
...but just compiling from source would link with libc on YOUR system and solve the issue.
```sh
$ cargo build --release
```

**Comment by Kihau** [comment]
You can compile for the `x86_64-unknown-linux-musl` target or statically link glibc to emit binary that works on all linux systems...
```sh
$ cargo build --target x86_64-unknown-linux-musl --release
```
...but just compiling from source would link with libc on YOUR system and solve the issue.
```sh
$ cargo build --release
```
